---
- hosts: managers
  gather_facts: true
  roles:
    - kubelet
    - kubeadm
    - calico
    - kubectl
    - helm
    - nvidia-gpu-operator
  environment: "{{env}}"
- hosts: workers
  gather_facts: true
  roles:
    - kubelet
    - nvidia-gpu-operator
  environment: "{{env}}"

