---
- hosts: managers
  gather_facts: true
  roles:
    - kubelet
    - kubectl
    - kubeadm
    - calico
    - helm
  environment: "{{env}}"
- hosts: workers
  gather_facts: true
  roles:
    - kubelet
  environment: "{{env}}"
- hosts: gpu_operators
  gather_facts: true
  roles:
    - nvidia-gpu-operator
  environment: "{{env}}"
