# kubeadm/tasks/init.yml
---
- name: Reset Kubernetes cluster
  shell: "kubeadm reset --force"
  register: reset_cluster
  become: true

- name: Initialize Kubernetes cluster
  when: reset_cluster is succeeded
  command: "kubeadm init --pod-network-cidr {{ pod_network_cidr }} {{ kubeadm_opts }} {{ init_opts }}"
  register: init_cluster
  become: true

- name: Create Kubernetes config directory
  file:
    path: .kube/
    state: directory
    mode: 0700

- name: Copy Kubernetes config
  when: init_cluster is succeeded
  copy:
    src: /etc/kubernetes/admin.conf
    dest: .kube/config
    mode: 0700
    remote_src: true
  become: true

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command to local file
  local_action: copy content= dest=join.sh
