# kubeadm/tasks/init.yml
---
- name: Reset Kubernetes cluster
  shell: "kubeadm reset --force"
  register: reset_cluster
  tags:
    - kubeadm
  become: true

- name: Initialize Kubernetes cluster
  when: reset_cluster is succeeded
  command: "kubeadm init {{ kubeadm_opts }}"
  register: init_cluster
  tags:
    - kubeadm
  become: true

- name: Create Kubernetes config directory
  file:
    path: .kube/
    state: directory
    mode: 0700
  tags:
    - kubeadm

- name: Copy Kubernetes config
  when: init_cluster is succeeded
  copy:
    src: /etc/kubernetes/admin.conf
    dest: .kube/config
    mode: 0700
    owner: "{{ ansible_real_user_id }}"
    group: "{{ ansible_real_group_id }}"
    remote_src: true
  tags:
    - kubeadm
  become: true

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command
  tags:
    - kubeadm
  become: true

- name: Copy join command to local file
  local_action: copy content={{ join_command.stdout }} dest=join-{{ ansible_host }}.sh
  tags:
    - kubeadm
