---
- name: Install Docker
  block:
    - when: ansible_os_family == "Debian" and ansible_pkg_mgr == "apt"
      block:
        - name: Install Docker dependencies
          apt:
            name: "{{ packages }}"
            state: present
            update_cache: yes
          vars:
            packages:
              - apt-transport-https
              - ca-certificates
              - curl
              - gnupg-agent
              - software-properties-common

        - name: Add Docker APT GPG key
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

        - name: Add Docker APT repository
          apt_repository:
            repo: deb [arch={{ arch }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
            state: present

        - name: Install Docker 
          apt: 
            name: "{{ packages }}"
            state: present
            update_cache: yes
          vars:
            packages:
              - docker-ce 
              - docker-ce-cli 
              - containerd.io

        - name: Hold docker-ce version
          dpkg_selections:
            name: docker-ce
            selection: hold
          become: true

        - name: Hold docker-ce-cli version
          dpkg_selections:
            name: docker-ce-cli
            selection: hold

        - name: Hold containerd.io version
          dpkg_selections:
            name: containerd.io
            selection: hold
  become: true
  tags:
    - docker

- name: Start docker
  when: ansible_service_mgr == "systemd"
  systemd:
    name: docker
    daemon_reload: yes
    state: started
    enabled: yes
  notify:
    - docker status
  become: true
  tags:
    - docker
